# Inicialización de variables para desactivar plugins by default
SecAction \
    "id:100000,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    setvar:TX.nextcloud-rule-exclusions-plugin_enabled=0,\
    setvar:TX.dokuwiki-rule-exclusions-plugin_enabled=0,\
    setvar:TX.drupal-rule-exclusions-plugin_enabled=0,\
    setvar:TX.wordpress-rule-exclusions-plugin_enabled=0"
